// 🎭 COMPLETE AVATAR CODE FOR storage_service.dart
// Copy this entire _getDefaultAvatars() function and replace the existing one

List<Avatar> _getDefaultAvatars() {
  return [
    // ✨ FANTASY/MAGICAL (1-5)
    Avatar(
      id: 'elyas',
      name: 'Elyas',
      imagePath: 'assets/avatars/elyas/image.png',
      voiceType: 'en-US-1',
      personality: 'calm',
      bestFor: ['fantasy', 'mystery', 'literary'],
      voiceSpeed: 0.85,
      description: 'A young wizard with a calm demeanor and arcane knowledge',
    ),
    Avatar(
      id: 'mira',
      name: 'Mira',
      imagePath: 'assets/avatars/mira/image.png',
      voiceType: 'en-US-2',
      personality: 'gentle',
      bestFor: ['romance', 'fantasy', 'young-adult'],
      voiceSpeed: 0.9,
      description: 'A gentle mage whose voice brings warmth and comfort',
    ),
    Avatar(
      id: 'kael',
      name: 'Kael',
      imagePath: 'assets/avatars/kael/image.png',
      voiceType: 'en-US-3',
      personality: 'mysterious',
      bestFor: ['dark-fantasy', 'thriller', 'horror'],
      voiceSpeed: 0.8,
      description: 'A dark mage with an intense voice that captivates and chills',
    ),
    Avatar(
      id: 'thalos',
      name: 'Thalos',
      imagePath: 'assets/avatars/thalos/image.png',
      voiceType: 'en-US-4',
      personality: 'wise',
      bestFor: ['fantasy', 'adventure', 'literary'],
      voiceSpeed: 0.75,
      description: 'An ancient wizard whose voice carries wisdom and timeless knowledge',
    ),
    Avatar(
      id: 'lyra',
      name: 'Lyra',
      imagePath: 'assets/avatars/lyra/image.png',
      voiceType: 'en-US-5',
      personality: 'ethereal',
      bestFor: ['fantasy', 'romance', 'poetry'],
      voiceSpeed: 0.88,
      description: 'An ethereal sorceress whose voice feels like starlight and dreams',
    ),

    // 🌑 DARK/MYSTERY (6-10)
    Avatar(
      id: 'victor',
      name: 'Victor',
      imagePath: 'assets/avatars/victor/image.png',
      voiceType: 'en-US-6',
      personality: 'analytical',
      bestFor: ['mystery', 'thriller', 'sci-fi'],
      voiceSpeed: 0.92,
      description: 'An analytical observer whose voice dissects every detail with precision',
    ),
    Avatar(
      id: 'noir',
      name: 'Noir',
      imagePath: 'assets/avatars/noir/image.png',
      voiceType: 'en-US-7',
      personality: 'mysterious',
      bestFor: ['noir', 'thriller', 'mystery'],
      voiceSpeed: 0.86,
      description: 'A shadowy figure whose voice echoes with secrets and darkness',
    ),
    Avatar(
      id: 'elena',
      name: 'Elena',
      imagePath: 'assets/avatars/elena/image.png',
      voiceType: 'en-US-8',
      personality: 'determined',
      bestFor: ['adventure', 'action', 'survival'],
      voiceSpeed: 0.95,
      description: 'A strong survivor whose voice carries determination and resilience',
    ),
    Avatar(
      id: 'marcus',
      name: 'Marcus',
      imagePath: 'assets/avatars/marcus/image.png',
      voiceType: 'en-US-9',
      personality: 'focused',
      bestFor: ['noir', 'mystery', 'crime'],
      voiceSpeed: 0.88,
      description: 'A seasoned detective whose voice cuts through deception with precision',
    ),
    Avatar(
      id: 'raven',
      name: 'Raven',
      imagePath: 'assets/avatars/raven/image.png',
      voiceType: 'en-US-10',
      personality: 'eerie',
      bestFor: ['horror', 'dark-fantasy', 'thriller'],
      voiceSpeed: 0.82,
      description: 'An otherworldly entity whose voice unsettles and haunts the listener',
    ),

    // 💕 ROMANCE/LITERARY (11-15)
    Avatar(
      id: 'clara',
      name: 'Clara',
      imagePath: 'assets/avatars/clara/image.png',
      voiceType: 'en-US-11',
      personality: 'comforting',
      bestFor: ['romance', 'drama', 'literary'],
      voiceSpeed: 0.87,
      description: 'A warm-hearted narrator whose voice brings comfort and peace',
    ),
    Avatar(
      id: 'julien',
      name: 'Julien',
      imagePath: 'assets/avatars/julien/image.png',
      voiceType: 'en-US-12',
      personality: 'romantic',
      bestFor: ['romance', 'literary', 'drama'],
      voiceSpeed: 0.89,
      description: 'A romantic soul whose voice captures passion and tenderness',
    ),
    Avatar(
      id: 'amelie',
      name: 'Amélie',
      imagePath: 'assets/avatars/amelie/image.png',
      voiceType: 'en-US-13',
      personality: 'whimsical',
      bestFor: ['fantasy', 'literary', 'poetry'],
      voiceSpeed: 0.84,
      description: 'An artistic dreamer whose voice paints vivid scenes and emotions',
    ),
    Avatar(
      id: 'leo',
      name: 'Leo',
      imagePath: 'assets/avatars/leo/image.png',
      voiceType: 'en-US-14',
      personality: 'friendly',
      bestFor: ['adventure', 'young-adult', 'comedy'],
      voiceSpeed: 0.93,
      description: 'A friendly companion whose voice feels like a trusted friend',
    ),
    Avatar(
      id: 'sofia',
      name: 'Sofia',
      imagePath: 'assets/avatars/sofia/image.png',
      voiceType: 'en-US-15',
      personality: 'thoughtful',
      bestFor: ['literary', 'drama', 'mystery'],
      voiceSpeed: 0.85,
      description: 'A thoughtful sage whose voice reveals profound wisdom and emotion',
    ),

    // 🔮 SCI-FI/CYBERPUNK (16-20)
    Avatar(
      id: 'zane',
      name: 'Zane',
      imagePath: 'assets/avatars/zane/image.png',
      voiceType: 'en-US-16',
      personality: 'futuristic',
      bestFor: ['sci-fi', 'cyberpunk', 'thriller'],
      voiceSpeed: 1.0,
      description: 'A cyberpunk rebel whose voice crackles with digital intensity',
    ),
    Avatar(
      id: 'nova',
      name: 'Nova',
      imagePath: 'assets/avatars/nova/image.png',
      voiceType: 'en-US-17',
      personality: 'ethereal',
      bestFor: ['sci-fi', 'literary', 'mystery'],
      voiceSpeed: 0.88,
      description: 'An artificial intelligence with a voice that transcends humanity',
    ),
    Avatar(
      id: 'orion',
      name: 'Orion',
      imagePath: 'assets/avatars/orion/image.png',
      voiceType: 'en-US-18',
      personality: 'adventurous',
      bestFor: ['sci-fi', 'adventure', 'fantasy'],
      voiceSpeed: 0.91,
      description: 'A space explorer whose voice echoes across galaxies and dreams',
    ),
    Avatar(
      id: 'kira',
      name: 'Kira',
      imagePath: 'assets/avatars/kira/image.png',
      voiceType: 'en-US-19',
      personality: 'intense',
      bestFor: ['cyberpunk', 'thriller', 'sci-fi'],
      voiceSpeed: 1.05,
      description: 'A brilliant hacker whose voice crackles with energy and intelligence',
    ),
    Avatar(
      id: 'atlas',
      name: 'Atlas',
      imagePath: 'assets/avatars/atlas/image.png',
      voiceType: 'en-US-20',
      personality: 'powerful',
      bestFor: ['sci-fi', 'mystery', 'thriller'],
      voiceSpeed: 0.86,
      description: 'A supreme intelligence whose voice carries absolute authority and power',
    ),

    // 👥 DIVERSE/CONTEMPORARY (21-25)
    Avatar(
      id: 'zoe',
      name: 'Zoé',
      imagePath: 'assets/avatars/zoe/image.png',
      voiceType: 'en-US-21',
      personality: 'rebellious',
      bestFor: ['young-adult', 'adventure', 'coming-of-age'],
      voiceSpeed: 1.02,
      description: 'A rebellious teen whose voice captures youthful passion and energy',
    ),
    Avatar(
      id: 'mamie_rose',
      name: 'Mamie Rose',
      imagePath: 'assets/avatars/mamie_rose/image.png',
      voiceType: 'en-US-22',
      personality: 'nurturing',
      bestFor: ['literary', 'drama', 'coming-of-age'],
      voiceSpeed: 0.78,
      description: 'A grandmother\'s voice that wraps you in warmth and timeless wisdom',
    ),
    Avatar(
      id: 'david',
      name: 'David',
      imagePath: 'assets/avatars/david/image.png',
      voiceType: 'en-US-23',
      personality: 'protective',
      bestFor: ['adventure', 'action', 'drama'],
      voiceSpeed: 0.90,
      description: 'A protective guardian whose voice brings safety and strength',
    ),
    Avatar(
      id: 'lina',
      name: 'Lina',
      imagePath: 'assets/avatars/lina/image.png',
      voiceType: 'en-US-24',
      personality: 'caring',
      bestFor: ['literary', 'drama', 'family'],
      voiceSpeed: 0.86,
      description: 'A loving mother whose voice carries unconditional warmth and care',
    ),
    Avatar(
      id: 'alex',
      name: 'Alex',
      imagePath: 'assets/avatars/alex/image.png',
      voiceType: 'en-US-25',
      personality: 'approachable',
      bestFor: ['young-adult', 'comedy', 'literary'],
      voiceSpeed: 0.94,
      description: 'An approachable friend whose voice feels genuinely conversational',
    ),
  ];
}
